15- Matrices , Fail fast-> false, tag

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -6,18 +6,33 @@ jobs:
         runs-on: ${{matrix.os}}
         name: ${{matrix.os}} - ${{matrix.node-version}}
         strategy:
+            # Default is true, whenever single job  is failed other job will be interepted.
+            fail-fast: false 
             matrix:
                 node-version: [18.x, 20.x, 21.x]
                 os: 
                     - ubuntu-latest
                     - windows-latest
+                include:
+                    - os: ubuntu-latest
+                      node-version: 16.x
+                    - os: ubuntu-latest
+                      node-version: 20.x
+                      tag: expriemental 
         steps:
             - name: Setup node
               uses: actions/setup-node@v3
               with: 
                 node-version: ${{matrix.node-version}}
+            - name: Fail if expriemental
+              if: ${{matrix.tag == 'expriemental'}}
+              run: exit 1
             - name: Perform some tests
-              run: echo "Running tests on OS  ${{matrix.os}}  and NodeJS  ${{matrix.node-version}}"
+              run: |
+                echo "Running tests on OS  ${{matrix.os}}  and NodeJS  ${{matrix.node-version}}"
+                sleep 10
+            - name: Upload test results
+              run: echo "Uploading the test result"
               
         
                 
